version: '2.0'
services:

  acs:
    image: registry.cn-hangzhou.aliyuncs.com/franky/acs
    ports:
      - "7557:7557"
    volumes:
      - ./acs:/app/genieacs

  gui:
    image: registry.cn-hangzhou.aliyuncs.com/franky/acs-gui
    ports:
      - "3000:3000"
    volumes:
      - ./acs:/app/genieacs-gui


    
  # acs:
  #   build: ./acs
  #   ports:
  #     - "7557:7557"
  #   volumes:
  #     - ./acs:/app/genieacs

  # gui:
  #   build: ./gui
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./acs:/app/genieacs-gui

